server:
  port: 12306

spring:
  activemq:
    broker-url: tcp://192.168.203.200:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false # 默认就是 false，false=Queue，true=Topic
    template:
      delivery-mode: persistent


# 自定义队列名称
myqueue: activemq-boot-queue